#!/bin/bash
# Build an UNSIGNED .ipa for TumoCompanion.
# Sign it afterwards with your developer cert via Feather Pro / Sideloadly.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
XCODE="/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild"
PATH="/opt/homebrew/bin:$PATH"
XCODE_JOBS="${XCODE_JOBS:-2}"

VERSION=$(awk -F'"' '/MARKETING_VERSION:/{print $2; exit}' project.yml)
STAMP="${BUILD_STAMP:-$(date +%Y%m%d-%H%M)}"
echo "==> Stamping BuildInfo: v$VERSION · $STAMP"
cat > Sources/App/BuildInfo.swift <<EOF
import Foundation

/// Generated by scripts/build_ipa.sh on every build. The timestamp makes each
/// build uniquely identifiable so we can confirm which IPA is on the device.
enum BuildInfo {
    static let version = "$VERSION"
    static let build = "$STAMP"
    static var label: String { "v\\(version) · \\(build)" }
}
EOF

echo "==> Regenerating project (XcodeGen)"
xcodegen generate

echo "==> Resolving Swift packages"
"$XCODE" -resolvePackageDependencies \
  -project UnleashedCompanion.xcodeproj -scheme UnleashedCompanion >/dev/null

echo "==> Building (Release, iphoneos, unsigned)"
"$XCODE" build \
  -project UnleashedCompanion.xcodeproj -scheme UnleashedCompanion \
  -sdk iphoneos -configuration Release -destination 'generic/platform=iOS' \
  -jobs "$XCODE_JOBS" \
  CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO | tail -3

APP=$("$XCODE" -project UnleashedCompanion.xcodeproj -scheme UnleashedCompanion \
  -sdk iphoneos -configuration Release -showBuildSettings -json 2>/dev/null \
  | python3 -c '
import json
import os
import sys

settings = next(
    (item["buildSettings"] for item in json.load(sys.stdin)
     if item.get("target") == "UnleashedCompanion"),
    None,
)
if settings is None:
    raise SystemExit("UnleashedCompanion build settings not found")
print(os.path.join(settings["TARGET_BUILD_DIR"], settings["FULL_PRODUCT_NAME"]))
')

if [ ! -d "$APP" ] || [ "${APP##*.}" != "app" ]; then
  echo "error: expected UnleashedCompanion.app, got: $APP" >&2
  exit 1
fi
if [ "$(plutil -extract CFBundlePackageType raw "$APP/Info.plist")" != "APPL" ]; then
  echo "error: build product is not an iOS application: $APP" >&2
  exit 1
fi

# Ad-hoc sign with the App Group entitlements EMBEDDED, so a re-signer (Feather /
# AltStore / Sideloadly) reads `com.apple.security.application-groups` from the
# existing signature and carries it into its own signature — without this the
# home-screen widgets get no shared container ("Widgets: unavailable"). Sign nested
# code first (frameworks, then the widget appex), then the outer app.
echo "==> Embedding App Group entitlements (ad-hoc)"
APPEX="$APP/PlugIns/UnleashedWidgets.appex"
if [ -d "$APP/Frameworks" ]; then
  for fw in "$APP/Frameworks/"*; do
    [ -e "$fw" ] && codesign --force --sign - --timestamp=none "$fw" >/dev/null 2>&1 || true
  done
fi
if [ -d "$APPEX" ]; then
  codesign --force --sign - --timestamp=none \
    --entitlements "$ROOT/Widgets/UnleashedWidgets.entitlements" "$APPEX"
  echo "    widget appex app-groups: $(codesign -d --entitlements - "$APPEX" 2>/dev/null | grep -c application-groups)"
fi
codesign --force --sign - --timestamp=none \
  --entitlements "$ROOT/Resources/UnleashedCompanion.entitlements" "$APP"
echo "    app app-groups: $(codesign -d --entitlements - "$APP" 2>/dev/null | grep -c application-groups)"

echo "==> Packaging IPA from $APP"
rm -rf build/ipa
mkdir -p build/ipa/Payload
cp -R "$APP" build/ipa/Payload/
( cd build/ipa && zip -qr "$ROOT/build/TumoCompanion-unsigned.ipa" Payload )

echo "==> Done: build/TumoCompanion-unsigned.ipa"
ls -lh build/TumoCompanion-unsigned.ipa
