#!/usr/bin/env python3
"""Export the Module One routing map from the app source into routing/module_one_routes.json.

The map (`PluginInstallRouting.targetPaths`) is hand-maintained in Swift; this turns it into
JSON the CI drift-check can read (issue #11). Run it whenever you edit the map:

    python3 scripts/export_routing_map.py [path/to/PluginUpdater.swift]

The default source path targets the Swift sources in this repository.
"""
import json
import pathlib
import re
import sys

DEFAULT_SRC = "Sources/Features/Updates/PluginUpdater.swift"


def main() -> int:
    src = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC)
    if not src.exists():
        print(f"error: source not found: {src}", file=sys.stderr)
        return 1

    text = src.read_text()
    block = re.search(r"targetPaths:\s*\[String:\s*String\]\s*=\s*\[\n(.*?)\n\s*\]", text, re.S)
    if not block:
        print("error: could not locate PluginInstallRouting.targetPaths", file=sys.stderr)
        return 1

    routes = dict(re.findall(r'"([^"]+)"\s*:\s*"([^"]+)"', block.group(1)))
    if not routes:
        print("error: parsed an empty map — check the regex / source", file=sys.stderr)
        return 1

    out = {
        "_comment": "Generated by scripts/export_routing_map.py from "
                    "PluginInstallRouting.targetPaths. Do not edit by hand.",
        "source": "Sources/Features/Updates/PluginUpdater.swift",
        "count": len(routes),
        "routes": dict(sorted(routes.items())),
    }
    dest = pathlib.Path("routing/module_one_routes.json")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {dest} with {len(routes)} routes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
